version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: app
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: always
    depends_on:
      - app
    ports:
      - 80:80

volumes:
  node_modules:
